name: test_app
description: "A new Flutter project."
publish_to: 'none'

version: 0.3.1+6

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/tap_sound.mp3
